### PR TITLE
Bump GHC prim upper bound

### PR DESCRIPTION
**Pull request by newhoggy**
In order to compile on `ghc-8.10.1`

### CODE REVIEW

**Comment by newhoggy** [comment]
Request new revision here: https://github.com/haskell-infra/hackage-trustees/issues/263

**Comment by newhoggy** [comment]
Confirmed builds locally for me:

```bash
$ cabal v2-build
Resolving dependencies...
Build profile: -w ghc-8.10.1 -O1
In order, the following will be built (use -v for more details):
 - retry-0.8.1.0 (lib) (first run)
Configuring library for retry-0.8.1.0..
Preprocessing library for retry-0.8.1.0..
Building library for retry-0.8.1.0..
[1 of 1] Compiling Control.Retry    ( src/Control/Retry.hs, /Users/jky/wrk/haskell-works/retry/dist-newstyle/build/x86_64-osx/ghc-8.10.1/retry-0.8.1.0/build/Control/Retry.o, /Users/jky/wrk/haskell-works/retry/dist-newstyle/build/x86_64-osx/ghc-8.10.1/retry-0.8.1.0/build/Control/Retry.dyn_o )
```

**Comment by MichaelXavier** [comment]
Thanks for raising this issue. However, in these situations I just prefer to remove the upper bound and deal with issues if and when they come up, which is usually pretty unlikely. I've released 0.8.1.1 which you should be able to use.

**Comment by newhoggy** [comment]
Thanks!

**Pull request closed without merging**
