### PR TITLE
remove data-default-class dependency

### PR DESCRIPTION
**Pull request by ocramz**
* Remove dependency
* Define and export `retryPolicyDefault`
* bump bugfix version number
* update changelog

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Isn't this a B version change and not C since you're removing a typeclass instance and thus breaking API?

**Comment by ocramz** [comment]
Good point, will fix. What do you think of the change overall?

**Comment by MichaelXavier** [comment]
I'm for it. I hate data-default. I actually kind of question the wisdom of the meaning of a "default" retry policy, but I'd rather it be an exported value than a typeclass instance.

**Comment by ocramz** [comment]
(The build failure against Nightly is due to #61 )

**Comment by MichaelXavier** [comment]
Thanks!

**Pull request merged**
