### PR TITLE
Allow exceptions 0.7.* and 0.8.*

### PR DESCRIPTION
**Pull request by bergmark**

### CODE REVIEW

**Comment by bergmark** [comment]
Refs https://github.com/fpco/stackage/issues/443

**Comment by ozataman** [comment]
Thanks.

**Comment by snoyberg** [comment]
Can you ping me when this is released to Hackage?

**Comment by ozataman** [comment]
@snoyberg This is released, but it coincided with a bump from 0.5 to 0.6, which requires MonadMask instead of MonadCatch in the recovering combinator. If you need 0.5 with broader deps, let me know and we can release a 0.5.1 with the old MonadCatch requirement.

**Comment by snoyberg** [comment]
I think this is fine as-is, thanks.

**Pull request merged**
